# Change these first
owner: artbanx-monitoring # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Website
    url: https://artbanx.io

  - name: App
    url: https://app.artbanx.io

  - name: User Login
    url: https://app.artbanx.io/auth/rest/public/authentication/password/check
    method: POST
    headers:
      - "X-Same-Domain: 1"
      - "Content-Type: application/json"
    body: '{ "username" : "$LOGIN_USERNAME", "password" : "$LOGIN_PASSWORD" }'
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

  - name: Collections and Permissions API
    url: https://app.artbanx.io/health/front-api/
    headers:
      - "$HEALTH_BASIC_AUTH_HEADER"
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200 

  - name: Art Data API
    url: https://app.artbanx.io/health/front-api/
    headers:
      - "$HEALTH_BASIC_AUTH_HEADER"
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200 

  - name: Payments API
    url: https://app.artbanx.io/health/payment/
    headers:
      - "$HEALTH_BASIC_AUTH_HEADER"
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

  - name: Identity and Screening API
    url: https://app.artbanx.io/health/kyc/
    headers:
      - "$HEALTH_BASIC_AUTH_HEADER"
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

  - name: Shipments API
    url: https://app.artbanx.io/health/shipping/
    headers:
      - "$HEALTH_BASIC_AUTH_HEADER"
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

  - name: Service Orchestration
    url: https://app.artbanx.io/health/offering/
    headers:
      - "$HEALTH_BASIC_AUTH_HEADER"
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200      

  - name: Virtual Gallery
    url: https://app.artbanx.io/health/virtual-gallery/
    headers:
      - "$HEALTH_BASIC_AUTH_HEADER"
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200                              
               
               
commitMessages:
  commitAuthorName: "Artbanx-Status-Bot"
  commitAuthorEmail: "monitoring@artbanx.io"

assignees: # Users to assign downtime issues (optional)
  - artbanx-monitoring
  - tino-fernandez

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: "status.artbanx.io"
  #baseUrl: /status-page
  publish: true
  logoUrl: https://cdn.statically.io/gh/artbanx-monitoring/status-page/master/assets/logo_small_grey.svg
  favicon: https://cdn.statically.io/gh/artbanx-monitoring/status-page/master/assets/favicon.ico
  name: Artbanx Services Status
  introTitle: "**Artbanx** Services Status"
  introMessage: Status page for Artbanx online services
  themeUrl: https://cdn.statically.io/gh/artbanx-monitoring/status-page/master/assets/artbanx-theme.css
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://artbanx.io
    - title: App
      href: https://app.artbanx.io   

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
